export { default as Authorized } from './Authorized'
export { default as Header } from './Header'
export { default as SlideMenu } from './SlideMenu'
export { default as IconFont } from './IconFont'
export { default as UpdateWin } from './UpdatePwd'
export { default as Account } from './Account'
export { default as NavTab } from './NavTab'
